force-app/main/default/objects/Roundup__c/Roundup__c.object-meta.xml
<CustomObject>
    <label>Roundup</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roundup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Roundup__c/fields/Age_at_Diagnosis__c.field-meta.xml
<CustomField>
    <fullName>Age_at_Diagnosis__c</fullName>
    <label>Age at Diagnosis</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Any_Other_Tobacco_Products__c.field-meta.xml
<CustomField>
    <fullName>Any_Other_Tobacco_Products__c</fullName>
    <label>Any Other Tobacco Products</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Are_you_a_smoker__c.field-meta.xml
<CustomField>
    <fullName>Are_you_a_smoker__c</fullName>
    <label>Are you a smoker?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Begin_Smoking_Date__c.field-meta.xml
<CustomField>
    <fullName>Begin_Smoking_Date__c</fullName>
    <label>Begin Smoking Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Caller_Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Caller_Date_of_Birth__c</fullName>
    <label>Caller Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Cause_of_Death__c.field-meta.xml
<CustomField>
    <fullName>Cause_of_Death__c</fullName>
    <label>Cause of Death</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/City_and_State_Deceased__c.field-meta.xml
<CustomField>
    <fullName>City_and_State_Deceased__c</fullName>
    <label>City and State Deceased</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Confirm_Date_of_Death__c.field-meta.xml
<CustomField>
    <fullName>Confirm_Date_of_Death__c</fullName>
    <label>Confirm Date of Death</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DOD confirmed</fullName>
            </value>
            <value>
                <fullName>DOD not confirmed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Current_Representation__c.field-meta.xml
<CustomField>
    <fullName>Current_Representation__c</fullName>
    <label>Current Representation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes (DNQ)</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Diagnosed_Before_2004__c.field-meta.xml
<CustomField>
    <fullName>Diagnosed_Before_2004__c</fullName>
    <label>Diagnosed Before 2004</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes (DNQ)</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Diagnosed_Before_2014__c.field-meta.xml
<CustomField>
    <fullName>Diagnosed_Before_2014__c</fullName>
    <label>Diagnosed Before 2014</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes (DNQ)</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Diagnosed_with_NHL__c.field-meta.xml
<CustomField>
    <fullName>Diagnosed_with_NHL__c</fullName>
    <label>Diagnosed with NHL</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Emergency_Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>Emergency_Contact_Phone__c</fullName>
    <label>Emergency Contact Phone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Emergency_Contact_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Emergency_Contact_Relationship__c</fullName>
    <label>Emergency Contact Relationship</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Employer_Address__c.field-meta.xml
<CustomField>
    <fullName>Employer_Address__c</fullName>
    <label>Employer Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Employer_Name__c.field-meta.xml
<CustomField>
    <fullName>Employer_Name__c</fullName>
    <label>Employer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Employer_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Employer_Phone_Number__c</fullName>
    <label>Employer Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/First_Treatment_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Treatment_Date__c</fullName>
    <label>First Treatment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Height_at_Date_of_Diagnosis__c.field-meta.xml
<CustomField>
    <fullName>Height_at_Date_of_Diagnosis__c</fullName>
    <label>Height at Date of Diagnosis</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Injured_Contact_Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Injured_Contact_Date_of_Birth__c</fullName>
    <label>Injured Contact Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Injured_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Injured_Contact_Name__c</fullName>
    <label>Injured Contact Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Injured_Party_Deceased__c.field-meta.xml
<CustomField>
    <fullName>Injured_Party_Deceased__c</fullName>
    <label>Injured Party Deceased</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Injured_Party_Gender__c.field-meta.xml
<CustomField>
    <fullName>Injured_Party_Gender__c</fullName>
    <label>Injured Party Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Last_Treatment_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Treatment_Date__c</fullName>
    <label>Last Treatment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Roundup</relationshipLabel>
    <relationshipName>Roundup</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Medical_Record_Available__c.field-meta.xml
<CustomField>
    <fullName>Medical_Record_Available__c</fullName>
    <label>Medical Record Available</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/NHL_Diagnosis_Stage__c.field-meta.xml
<CustomField>
    <fullName>NHL_Diagnosis_Stage__c</fullName>
    <label>NHL Diagnosis Stage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/NHL_Diagnosis_Year__c.field-meta.xml
<CustomField>
    <fullName>NHL_Diagnosis_Year__c</fullName>
    <label>NHL Diagnosis Year</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/NHL_Subtype__c.field-meta.xml
<CustomField>
    <fullName>NHL_Subtype__c</fullName>
    <label>NHL Subtype</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Occupation__c.field-meta.xml
<CustomField>
    <fullName>Occupation__c</fullName>
    <label>Occupation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agriculture Worker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Oncologist_Information__c.field-meta.xml
<CustomField>
    <fullName>Oncologist_Information__c</fullName>
    <label>Oncologist Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Packs_of_Cigarettes_Per_Day__c.field-meta.xml
<CustomField>
    <fullName>Packs_of_Cigarettes_Per_Day__c</fullName>
    <label>Packs of Cigarettes Per Day</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/PCP_Information__c.field-meta.xml
<CustomField>
    <fullName>PCP_Information__c</fullName>
    <label>PCP Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Power_of_Attorney__c.field-meta.xml
<CustomField>
    <fullName>Power_of_Attorney__c</fullName>
    <label>Power of Attorney</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Pre_existing_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Pre_existing_Conditions__c</fullName>
    <label>Pre-existing Conditions</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agent Orange Exposure</fullName>
            </value>
            <value>
                <fullName>Hepatitis B or C Diagnosis</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Provider_Address__c.field-meta.xml
<CustomField>
    <fullName>Provider_Address__c</fullName>
    <label>Provider Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Provider_Name__c.field-meta.xml
<CustomField>
    <fullName>Provider_Name__c</fullName>
    <label>Provider Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Provider_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Provider_Phone_Number__c</fullName>
    <label>Provider Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Quit_Smoking_Date__c.field-meta.xml
<CustomField>
    <fullName>Quit_Smoking_Date__c</fullName>
    <label>Quit Smoking Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Referral_Law_Firm__c.field-meta.xml
<CustomField>
    <fullName>Referral_Law_Firm__c</fullName>
    <label>Referral Law Firm</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Relationship_with_Injured_Contact__c.field-meta.xml
<CustomField>
    <fullName>Relationship_with_Injured_Contact__c</fullName>
    <label>Relationship with Injured Contact</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Roundup_Usage_Location__c.field-meta.xml
<CustomField>
    <fullName>Roundup_Usage_Location__c</fullName>
    <label>Roundup Usage Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/State_of_Residence_during_Treatments__c.field-meta.xml
<CustomField>
    <fullName>State_of_Residence_during_Treatments__c</fullName>
    <label>State of Residence during Treatments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/States_Roundup_Used__c.field-meta.xml
<CustomField>
    <fullName>States_Roundup_Used__c</fullName>
    <label>States Roundup Used</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Surgeon_Information__c.field-meta.xml
<CustomField>
    <fullName>Surgeon_Information__c</fullName>
    <label>Surgeon Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Treatment_Received__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Received__c</fullName>
    <label>Treatment Received</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Weight_at_Date_of_Diagnosis__c.field-meta.xml
<CustomField>
    <fullName>Weight_at_Date_of_Diagnosis__c</fullName>
    <label>Weight at Date of Diagnosis</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Years_Smoked__c.field-meta.xml
<CustomField>
    <fullName>Years_Smoked__c</fullName>
    <label>Years Smoked</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RoundupTriggerHandler.cls
public class RoundupTriggerHandler {
    
    public static void sendDataToSmartAdvocate(Id recordId) {
		List <Roundup__c> newRecord = [SELECT Id, OwnerId, Lead__r.CreatedDate, Name, Power_of_Attorney__c, City_and_State_Deceased__c, Confirm_Date_of_Death__c,
                Occupation__c, Begin_Smoking_Date__c, Years_Smoked__c, Packs_of_Cigarettes_Per_Day__c, Any_Other_Tobacco_Products__c, Quit_Smoking_Date__c,
                Injured_Party_Gender__c, Referral_Law_Firm__c , Best_Time_to_Reach__c, Caller_Date_of_Birth__c, Emergency_Contact_Name__c, Weight_at_Date_of_Diagnosis__c, Height_at_Date_of_Diagnosis__c,  
                Emergency_Contact_Relationship__c, Relationship_with_Injured_Contact__c, Emergency_Contact_Phone__c, 
                Injured_Contact_Name__c, Injured_Contact_Date_of_Birth__c, Current_Representation__c, Diagnosed_with_NHL__c, 
                NHL_Subtype__c, NHL_Diagnosis_Year__c, NHL_Diagnosis_Stage__c, Injured_Party_Deceased__c, Diagnosed_Before_2014__c, 
                Cause_of_Death__c, Diagnosed_Before_2004__c, Age_at_Diagnosis__c, Medical_Record_Available__c, Provider_Name__c, 
                Provider_Phone_Number__c, Provider_Address__c, Last_Treatment_Date__c, First_Treatment_Date__c, Surgeon_Information__c, 
                Oncologist_Information__c, PCP_Information__c, Treatment_Received__c, State_of_Residence_during_Treatments__c, 
                Pre_existing_Conditions__c, Are_you_a_smoker__c, States_Roundup_Used__c, Roundup_Usage_Location__c, Employer_Name__c, 
                Employer_Address__c, Employer_Phone_Number__c, Roundup_First_Exposure_Date__c, Roundup_Frequency_per_Year__c, 
                Roundup_Last_Exposure_Date__c, Roundup_Total_Years_Used__c, Roundup_Stop_Reason__c, Roundup_Exposure_Type__c, 
                Roundup_Type_Used__c, Roundup_Application_Method__c, Roundup_Application_Area_Size__c, Roundup_Purchase_Details__c,
                Chemotherapy_Treatment_Information__c, Chemotherapy_Start_Date__c, Chemotherapy_End_Date__c, Treatment_Provider_Name__c,
                Treatment_Provider_Address__c, Treatment_Provider_Phone__c, Additional_Specialist_Information__c, Surgeon_Name__c, Surgeon_Address__c,
                Oncologist_Name__c, Oncologist_Address__c, PCP_Name__c, PCP_Address__c, Proof_of_Purchase_Information__c, 
                Lead__c, Lead__r.Additional_Notes__c, Lead__r.Intake_Specialist__c, Lead__r.FirstName, Lead__r.LastName, Lead__r.Email,
                Lead__r.Phone, Lead__r.Address, Lead__r.Street, Lead__r.City, Lead__r.State, Lead__r.Country, Lead__r.PostalCode,
                Employer_City__c, Employer_State__c, Employer_Zip__c, Treatment_Provider_City__c, Treatment_Provider_State__c, Treatment_Provider_Zip__c,
                Surgeon_City__c, Surgeon_State__c, Surgeon_Zip__c, Oncologist_City__c, Oncologist_State__c, Oncologist_Zip__c, PCP_State__c, PCP_City__c, PCP_Zip__c,
                Additional_Medical_History__c, Lead__r.SSN__c FROM Roundup__c WHERE Id = :recordId];
        
        Lead relatedLead = [Select Id, Name from Lead where Id = :newRecord[0].Lead__c];
    	List<Object> roundupModels = SmartAdvocateModel.mapToSmartAdvocateFields(newRecord);
    	String smartAdvocateModelJson = JSON.serialize(roundupModels[0]);

    	// Asynchronously send data to the external system
        sendLeadDataWithDelay(smartAdvocateModelJson, relatedLead.Id);
   }
    
    public static void sendLeadDataWithDelay(String smartAdvocateModelJson, String leadId) {
        System.debug('Uslo u sendLeadDataWithDelay');
        // Introduce a delay before calling sendLeadDataAsync
        String year = String.valueOf(Datetime.now().year());
        String month = Datetime.now().format('MMM').toUpperCase();
        String day = String.valueOf(Datetime.now().day());
        String hour = String.valueOf(Datetime.now().hour());
		String min = String.valueOf(Datetime.now().minute() + 2);
		String ss = String.valueOf(Datetime.now().second());

        String nextFireTime = ss + ' ' + min + ' ' + hour + ' ' +  day + ' ' + month + ' ? ' + year;
        System.debug('nextFireTime ::: ' + nextFireTime);

        try {
        	System.schedule('ScheduleRoundupIntegration_' + leadId + System.now(), nextFireTime, new ScheduleRoundupIntegration(smartAdvocateModelJson, leadId));
        } catch (Exception ex) {
            System.debug( 'Error scheduling apex job : ' + ex.getMessage());            
        }
    }        
}