force-app/main/default/objects/Roundup__c/Roundup__c.object-meta.xml
<CustomObject>
    <label>Roundup</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roundup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Roundup__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Roundup</relationshipLabel>
    <relationshipName>Roundup</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RoundupTriggerTest.cls
@isTest
public class RoundupTriggerTest {
	@isTest
    static void testRoundupTrigger() {
		HttpCalloutMock mock = new HttpIntegrationMock();
        Test.setMock(HttpCalloutMock.class, mock);
        
        // Create a test Lead
        Lead testLead = new Lead(
            FirstName = 'John',
            LastName = 'Doe',
            Status = 'Retainer signed',
            Email = 'john.doe@example.com'
        );
        insert testLead;

        // Create a test Roundup record
        Roundup__c testRoundup = new Roundup__c(
            Lead__c = testLead.Id,
            Status__c = 'Some other status' // Set a status other than 'Retainer signed'
        );
        insert testRoundup;

        // Update the Roundup record to simulate a status change
        Test.startTest();
        testRoundup.Status__c = 'Retainer signed';
        update testRoundup;
		Test.stopTest();
        
        System.assertEquals('Retainer signed', testRoundup.Status__c);
    }
}