force-app/main/default/objects/Camp_Lejeune__c/Camp_Lejeune__c.object-meta.xml
<CustomObject>
    <label>Camp Lejeune</label>
    <nameField>
        <label>Camp Lejeune Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Camp Lejeune</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Camp_Lejeune__c/fields/Caller_Has_Authority_to_Sign__c.field-meta.xml
<CustomField>
    <fullName>Caller_Has_Authority_to_Sign__c</fullName>
    <label>Caller Has Authority to Sign?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Executor of estate</fullName>
            </value>
            <value>
                <fullName>POA</fullName>
            </value>
            <value>
                <fullName>NOK</fullName>
            </value>
            <value>
                <fullName>Spouse</fullName>
            </value>
            <value>
                <fullName>Guardianship</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Camp_Lejeune__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Camp Lejeune</relationshipLabel>
    <relationshipName>Camp_Lejeune</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Camp_Lejeune__c/fields/Next_Of_Kin__c.field-meta.xml
<CustomField>
    <fullName>Next_Of_Kin__c</fullName>
    <description>Are you the next of kin?</description>
    <inlineHelpText>Are you the next of kin?</inlineHelpText>
    <label>Next Of Kin</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Camp_Lejeune__c/fields/Other_Name__c.field-meta.xml
<CustomField>
    <fullName>Other_Name__c</fullName>
    <label>Other Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Camp_Lejeune__c/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <label>SSN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Camp_Lejeune__c/fields/Tier_1_Diagnoses__c.field-meta.xml
<CustomField>
    <fullName>Tier_1_Diagnoses__c</fullName>
    <label>Tier 1 Diagnoses</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bladder cancer</fullName>
            </value>
            <value>
                <fullName>Kidney cancer</fullName>
            </value>
            <value>
                <fullName>Liver cancer</fullName>
            </value>
            <value>
                <fullName>Non-Hodgkin lymphoma</fullName>
            </value>
            <value>
                <fullName>None of the above (tier 2,3,4)</fullName>
            </value>
            <value>
                <fullName>Parkinson&apos;s disease</fullName>
            </value>
            <value>
                <fullName>Leukemia (All types, adult or childhood)</fullName>
            </value>
            <value>
                <fullName>Kidney disease (End stage renal (ESRD), Renal Toxicity, Chronic Kidney Disease, etc.)</fullName>
            </value>
            <value>
                <fullName>Multiple myeloma and myelodysplastic Syndromes</fullName>
            </value>
            <value>
                <fullName>Systemic sclerosis</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Camp_Lejeune__c/fields/Tier_2_Diagnoses__c.field-meta.xml
<CustomField>
    <fullName>Tier_2_Diagnoses__c</fullName>
    <label>Tier 2 Diagnoses</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Esophageal cancer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Camp_Lejeune__c/fields/Tier_3_Diagnoses__c.field-meta.xml
<CustomField>
    <fullName>Tier_3_Diagnoses__c</fullName>
    <label>Tier 3 Diagnoses</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aplastic Anemia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Camp_Lejeune__c/fields/Tier_4_Diagnoses__c.field-meta.xml
<CustomField>
    <fullName>Tier_4_Diagnoses__c</fullName>
    <label>Tier 4 Diagnoses</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Camp_Lejeune__c/fields/Tier_5_Diagnoses__c.field-meta.xml
<CustomField>
    <fullName>Tier_5_Diagnoses__c</fullName>
    <label>Tier 5 Diagnoses</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Neurological effects (delayed reaction times problems with short-term memory, visual perception, attention, and color vision)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Additional_Notes__c.field-meta.xml
<CustomField>
    <fullName>Additional_Notes__c</fullName>
    <description>Additional Notes field from the FormStack</description>
    <label>Additional Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Caller_Recorded_Consent__c.field-meta.xml
<CustomField>
    <fullName>Caller_Recorded_Consent__c</fullName>
    <label>Caller Recorded Consent</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Calling_for_yourself__c.field-meta.xml
<CustomField>
    <fullName>Calling_for_yourself__c</fullName>
    <label>Calling for yourself?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Self</fullName>
            </value>
            <value>
                <fullName>Someone Else</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Contacting_Consent__c.field-meta.xml
<CustomField>
    <fullName>Contacting_Consent__c</fullName>
    <description>Do we have full consents to reach out via phone, automated call, SMS/Text and email?</description>
    <label>Contacting Consent</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Other_Name__c.field-meta.xml
<CustomField>
    <fullName>Other_Name__c</fullName>
    <label>Other Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Signature_Mail_Request__c.field-meta.xml
<CustomField>
    <fullName>Signature_Mail_Request__c</fullName>
    <label>Signature/Mail Request</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>E-Signature</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <label>SSN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Talc__c/Talc__c.object-meta.xml
<CustomObject>
    <label>Talc</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Talcs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Talc__c/fields/Any_other_significant_exposure__c.field-meta.xml
<CustomField>
    <fullName>Any_other_significant_exposure__c</fullName>
    <label>Any other significant exposure?</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Talc__c/fields/Injureds_Full_Legal_Name__c.field-meta.xml
<CustomField>
    <fullName>Injureds_Full_Legal_Name__c</fullName>
    <label>Injured&apos;s Full Legal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Talc__c/fields/Injury_diagnosed_with__c.field-meta.xml
<CustomField>
    <fullName>Injury_diagnosed_with__c</fullName>
    <description>First, I want to make sure that you have an injury that we believe is caused by exposure to talcum powder so that we can help you. What injury were you diagnosed with? *</description>
    <inlineHelpText>First, I want to make sure that you have an injury that we believe is caused by exposure to talcum powder so that we can help you. What injury were you diagnosed with? *</inlineHelpText>
    <label>Injury diagnosed with?</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Other</fullName>
                <default>true</default>
                <label>Other</label>
            </value>
            <value>
                <fullName>Breast Cancer (DNQ)</fullName>
            </value>
            <value>
                <fullName>Uterine Cancer</fullName>
            </value>
            <value>
                <fullName>Ovarian Cancer</fullName>
            </value>
            <value>
                <fullName>Vaginal Cancer</fullName>
            </value>
            <value>
                <fullName>Lung Cancer (DNQ)</fullName>
            </value>
            <value>
                <fullName>Endometrial Cancer</fullName>
            </value>
            <value>
                <fullName>Fallopian Tube Cancer</fullName>
            </value>
            <value>
                <fullName>Mesothelioma</fullName>
            </value>
            <value>
                <fullName>Uterine Fibroid (DNQ)</fullName>
            </value>
            <value>
                <fullName>Cervical Cancer</fullName>
            </value>
            <value>
                <fullName>Vulvar Cancer</fullName>
            </value>
            <value>
                <fullName>Hysterectomy (DNQ)</fullName>
            </value>
            <value>
                <fullName>Primary Peritoneal Cancer</fullName>
            </value>
            <value>
                <fullName>Carcinosarcoma</fullName>
            </value>
            <value>
                <fullName>Endometriosis (DNQ)</fullName>
            </value>
            <value>
                <fullName>Omentum Cancer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Talc__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>WattsGuerraTalcQuestionnaireV2FINAL_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Talc__c/fields/Next_Of_Kin__c.field-meta.xml
<CustomField>
    <fullName>Next_Of_Kin__c</fullName>
    <label>Next Of Kin</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Talc__c/fields/Spouse_s_Name__c.field-meta.xml
<CustomField>
    <fullName>Spouse_s_Name__c</fullName>
    <label>Spouse&apos;s Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Talc__c/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <label>SSN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tylenol__c/Tylenol__c.object-meta.xml
<CustomObject>
    <label>Tylenol</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tylenol</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tylenol__c/fields/Accurate_Information_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Accurate_Information_Agreement__c</fullName>
    <label>Accurate Information Agreement</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tylenol__c/fields/Child_s_SSN__c.field-meta.xml
<CustomField>
    <fullName>Child_s_SSN__c</fullName>
    <label>Child&apos;s SSN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tylenol__c/fields/Client_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Name__c</fullName>
    <label>Client Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tylenol__c/fields/Father_s_Age_at_Baby_s_Birth__c.field-meta.xml
<CustomField>
    <fullName>Father_s_Age_at_Baby_s_Birth__c</fullName>
    <label>Father&apos;s Age at Baby&apos;s Birth</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tylenol__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tylenol__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Tylenol</relationshipLabel>
    <relationshipName>Tylenol</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
public class TestDataFactory {
    
	public static Lead createTestLead() {
        Lead testLead = new Lead(
            FirstName = 'Test',
            LastName = 'Lead',
            City = 'TestCity',
            State = 'Alabama',
            Street = 'TestStreet',
            PostalCode = '12345',
            Phone = '123-456-7890',
            Email = 'test@example.com',
            Status = 'Qualified',
            Calling_for_yourself__c = 'Self',
            Signature_Mail_Request__c = 'Digital',
            Caller_Recorded_Consent__c = 'Yes',
            Contacting_Consent__c = 'Yes',
            Additional_Notes__c = 'Test notes'
        );
        insert testLead;
        return testLead;
    }

    public static Talc__c createTestTalc(Lead testLead) {
        //Lead testLead = createTestLead();
        Talc__c testTalc = new Talc__c(
            Lead__r = testLead,
            Lead__c = testLead.Id,
            Next_Of_Kin__c = 'Test Next of Kin',
            Injureds_Full_Legal_Name__c = 'Emina Test',
            Spouse_s_Name__c = 'Spouse Test',
            Any_other_significant_exposure__c = 'Test exposure',
            Injury_diagnosed_with__c = 'Mesothelioma;Primary Peritoneal;Fallopian Tube Cancer;Ovarian Cancer;Cervical Cancer;Uterine Cancer;Vaginal Cancer;Endometrial cancer'
        );
        insert testTalc;
        return testTalc;
    }

	public static Camp_Lejeune__c createTestCMPL(Lead testLead) {
        //Lead testLead = createTestLead();
        Camp_Lejeune__c testCMPL = new Camp_Lejeune__c(
            Lead__r = testLead,
            Lead__c = testLead.Id,
            Next_Of_Kin__c = 'Test Next of Kin',
            Other_Name__c = 'Emina Test',
            Caller_Has_Authority_to_Sign__c = 'POA',
            SSN__c = '123-444-5556',
            Tier_1_Diagnoses__c = 'Kidney cancer;Leukemia;Liver cancer;Parkinson;Systemic sclerosis;Non-Hodgkin lymphoma;Multiple myeloma and myelodysplastic Syndromes',
            Tier_2_Diagnoses__c = 'Esophageal cancer;Lung cancer;Miscarriage / Fetal Death;Congenital Cardiac Defect',
            Tier_3_Diagnoses__c = 'Aplastic Anemia;Brain cancer;Cervical cancer;Prostate cancer;Ovarian cancer;Liver Disease;Hodgkins Disease;Rectal Cancer;Soft Tissue Cancer / Sarcoma',
            Tier_4_Diagnoses__c = 'Neurobehavioral effects;ALS;Bile Duct Cancer;Colon Cancer;Laryngeal Cancer;Oral Cancer;Pharyngeal Cancer;Pancreatic Cancer;Thyroid Cancer;Autoimmune Disease',
            Tier_5_Diagnoses__c = 'Neurological effects;Neurobehavioral performance deficits;Infertility (Male or Female);Hypersensitivity Skin Disorder;Lupus;Multiple sclerosis'
            // Add other required fields here
        );
        insert testCMPL;
        return testCMPL;
    }
    
    public static Tylenol__c createTestTylenol(Lead testLead) {
        //Lead testLead = createTestLead();
        Tylenol__c testTyl = new Tylenol__c(
            Lead__r = testLead,
            Lead__c = testLead.Id,
            Accurate_Information_Agreement__c = 'Yes',
            Client_Name__c = 'Emina Test',
            Gender__c = 'Female',
            Child_s_SSN__c = '123-444-5556',
            Father_s_Age_at_Baby_s_Birth__c = '34'
            // Add other required fields here
        );
        insert testTyl;
        return testTyl;
    }
    
    public static ContentDocumentLink createTestContentDocument(Lead testLead) {
        //Lead testLead = createTestLead();
		ContentVersion testContentVersion = new ContentVersion(
            Title = 'Test Attachment.pdf',
            VersionData = Blob.valueOf('Test attachment content'),
            PathOnClient = 'Test Attachment.pdf'
        );
        insert testContentVersion;
        
        // Create a ContentDocumentLink record
        ContentDocumentLink testAttachmentLink = new ContentDocumentLink(
            ContentDocumentId = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id = :testContentVersion.Id].ContentDocumentId,
            LinkedEntityId = testLead.Id,
            ShareType = 'V'
        );
		insert testAttachmentLink;
        return testAttachmentLink;
    }
}