force-app/main/default/objects/HelloSign__SignerRole__c/HelloSign__SignerRole__c.object-meta.xml
<CustomObject>
    <label>Dropbox Sign Signer Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dropbox Sign Signer Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HelloSign__SignerRole__c/fields/HelloSign__SpecificEmail__c.field-meta.xml
<CustomField>
    <fullName>HelloSign__SpecificEmail__c</fullName>
    <description>Email field on the SignerRole__c custom object. Stores the email address for the SignerRole__c.</description>
    <label>Specific Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/HelloSign__SignerRole__c/fields/HelloSign__SpecificFirstName__c.field-meta.xml
<CustomField>
    <fullName>HelloSign__SpecificFirstName__c</fullName>
    <description>String field on the SignerRole__c custom object. Stores the specific first name for the SignerRole__c</description>
    <label>Specific First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HelloSign__SignerRole__c/fields/HelloSign__Template__c.field-meta.xml
<CustomField>
    <fullName>HelloSign__Template__c</fullName>
    <description>String field on the SignerRole__c custom object. Stores the parent template.</description>
    <label>Dropbox Sign Template</label>
    <referenceTo>HelloSign__Template__c</referenceTo>
    <relationshipLabel>Dropbox Sign Signer Roles</relationshipLabel>
    <relationshipName>Signer_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HelloSign__Template__c/HelloSign__Template__c.object-meta.xml
<CustomObject>
    <label>Dropbox Sign Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dropbox Sign Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HelloSign__Template__c/fields/HelloSign__Status__c.field-meta.xml
<CustomField>
    <fullName>HelloSign__Status__c</fullName>
    <description>String field on the Template custom object. The status of the template.  Includes: Draft, Pending, Active, Error, Archived.  Note this is set by automation and should not be changed manually.</description>
    <label>Status</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Talc__c/Talc__c.object-meta.xml
<CustomObject>
    <label>Talc</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Talcs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Talc__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>WattsGuerraTalcQuestionnaireV2FINAL_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SendSignatureRequestWithTemplateTest.cls
@isTest
public class SendSignatureRequestWithTemplateTest {
    @isTest
    static void testGenerateHelloSignature() {
        // Create a test HelloSign__Template__c record
        HelloSign__Template__c testTemplate = new HelloSign__Template__c(
            Name = 'Saddle Rock- Talcum Powder- Please sign',
            HelloSign__Status__c = 'Sent'
        );
        insert testTemplate;

        // Create a test HelloSign__SignerRole__c record associated with the template
        HelloSign__SignerRole__c testRole = new HelloSign__SignerRole__c(
            HelloSign__Template__c = testTemplate.Id,
            HelloSign__SpecificEmail__c = 'test@example.com',
            HelloSign__SpecificFirstName__c = 'Test'
        );
        insert testRole;

        Campaign relatedCampaign = new Campaign();
        relatedCampaign.Name = 'Talc';
        insert relatedCampaign;
        
        Account relatedCompany = new Account();
        relatedCompany.Name = 'Saddle Rock';
        insert relatedCompany;
        
        Lead leadObject = new Lead();
        leadObject.LastName = 'test';
        leadObject.Campaign__c = relatedCampaign.Id;
        leadObject.Company__c = relatedCompany.Id;
        insert leadObject;
        
        Talc__c talcObject = new Talc__c();
        talcObject.Lead__c = leadObject.Id;
        insert talcObject;

        Test.startTest();
        // Call the method with the test data
        sendSignatureReequestWithTemplate.generateHelloSignature('test@example.com', 'Test', talcObject.Id);
        Test.stopTest();
    }
}