force-app/main/default/objects/HelloSign__SignerRole__c/HelloSign__SignerRole__c.object-meta.xml
<CustomObject>
    <label>Dropbox Sign Signer Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dropbox Sign Signer Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HelloSign__SignerRole__c/fields/HelloSign__SpecificEmail__c.field-meta.xml
<CustomField>
    <fullName>HelloSign__SpecificEmail__c</fullName>
    <description>Email field on the SignerRole__c custom object. Stores the email address for the SignerRole__c.</description>
    <label>Specific Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/HelloSign__SignerRole__c/fields/HelloSign__SpecificFirstName__c.field-meta.xml
<CustomField>
    <fullName>HelloSign__SpecificFirstName__c</fullName>
    <description>String field on the SignerRole__c custom object. Stores the specific first name for the SignerRole__c</description>
    <label>Specific First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HelloSign__SignerRole__c/fields/HelloSign__Template__c.field-meta.xml
<CustomField>
    <fullName>HelloSign__Template__c</fullName>
    <description>String field on the SignerRole__c custom object. Stores the parent template.</description>
    <label>Dropbox Sign Template</label>
    <referenceTo>HelloSign__Template__c</referenceTo>
    <relationshipLabel>Dropbox Sign Signer Roles</relationshipLabel>
    <relationshipName>Signer_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HelloSign__Template__c/HelloSign__Template__c.object-meta.xml
<CustomObject>
    <label>Dropbox Sign Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dropbox Sign Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SendSignatureRequestWithTemplate.cls
public class SendSignatureRequestWithTemplate {
    
    public static void generateHelloSignature(String email, String name, Id talcId, String templateName){
        Id sfdcTemplateId = [SELECT Id FROM HelloSign__Template__c WHERE Name = :templateName][0]?.Id;
        
        List<HelloSign__SignerRole__c> role = [
            SELECT Id, HelloSign__SpecificEmail__c, HelloSign__SpecificFirstName__c
            FROM HelloSign__SignerRole__c
            WHERE HelloSign__Template__c = :sfdcTemplateId];
		
        for(HelloSign__SignerRole__c ro : role){
            ro.HelloSign__SpecificEmail__c = email;
            ro.HelloSign__SpecificFirstName__c = name;
        }
        update role;

        List<HelloSign.SendWithTemplate.SendObject> sos = 
          new List<HelloSign.SendWithTemplate.SendObject>();
        
        HelloSign.SendWithTemplate.SendObject so = 
          new HelloSign.SendWithTemplate.SendObject(talcId, sfdcTemplateId);
        sos.add(so);
        
        // Pass List to sendWithTemplate method
        HelloSign.SendWithTemplate.sendWithTemplate(sos);
    }
}