force-app/main/default/objects/HelloSign__HelloSign_Signature_Request__c/HelloSign__HelloSign_Signature_Request__c.object-meta.xml
<CustomObject>
    <description>Custom object for Dropbox Sign signature request records</description>
    <label>Dropbox Sign Signature Request</label>
    <nameField>
        <displayFormat>HELLO-{000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dropbox Sign Signature Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HelloSign__HelloSign_Signature_Request__c/fields/HelloSign__Lead__c.field-meta.xml
<CustomField>
    <fullName>HelloSign__Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>String field on the signature request record. Stores the Lead name of the agreement sent from Lead object</description>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>HelloSign_Document_Statuses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HelloSign__HelloSign_Signature_Request__c/fields/Talc__c.field-meta.xml
<CustomField>
    <fullName>Talc__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Talc</label>
    <referenceTo>Talc__c</referenceTo>
    <relationshipLabel>Dropbox Sign Signature Requests</relationshipLabel>
    <relationshipName>Dropbox_Sign_Signature_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HelloSign__HelloSign_Signature_Request_Detail__c/HelloSign__HelloSign_Signature_Request_Detail__c.object-meta.xml
<CustomObject>
    <label>Dropbox Sign Signature Request Detail</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Dropbox Sign Signature Request Detail Na</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dropbox Sign Signature Request Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HelloSign__HelloSign_Signature_Request_Detail__c/fields/HelloSign__Date__c.field-meta.xml
<CustomField>
    <fullName>HelloSign__Date__c</fullName>
    <description>Datetime field on the signature request detail record. Stores when the callback happens as part of the audit trail</description>
    <label>Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/HelloSign__HelloSign_Signature_Request_Detail__c/fields/HelloSign__Event__c.field-meta.xml
<CustomField>
    <fullName>HelloSign__Event__c</fullName>
    <description>Dropdown option on the signature request detail record. Values:
Sent: Created when the agreement has been sent a specific signer.
Condition: Ordered Signers → in the case of N total signers in an order, when signer(N-1) has &quot;signed&quot; then immeditaly &quot;sent&quot; would occur for signer (N)
Condition: Non-ordered signers → in the case of N total signers, in no order, upon sending the request each N signer should be documented as &quot;Sent&quot;

Viewed: Created when the agreement has been opened by a particular signer.

Signed: Created when the agreement has been signed by a specific signer

Declined: Created when the agreement has been successfully declined by signer including adding in a comment</description>
    <label>Event</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Viewed</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Reminded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HelloSign__HelloSign_Signature_Request_Detail__c/fields/HelloSign__HelloSign_Signature_Request__c.field-meta.xml
<CustomField>
    <fullName>HelloSign__HelloSign_Signature_Request__c</fullName>
    <description>String field on the signature request detail record. Stores the Id of the parent record.</description>
    <label>Dropbox Sign Signature Request</label>
    <referenceTo>HelloSign__HelloSign_Signature_Request__c</referenceTo>
    <relationshipLabel>Dropbox Sign Signature Request Details</relationshipLabel>
    <relationshipName>HelloSign_Document_Status_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Date_Retainer_Sent__c.field-meta.xml
<CustomField>
    <fullName>Date_Retainer_Sent__c</fullName>
    <label>Date Retainer Sent</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Date_Signed__c.field-meta.xml
<CustomField>
    <fullName>Date_Signed__c</fullName>
    <label>Date Signed</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Talc__c/Talc__c.object-meta.xml
<CustomObject>
    <label>Talc</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Talcs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Talc__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>WattsGuerraTalcQuestionnaireV2FINAL_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UpdateLeadSignedDateAndStatusTest.cls
@isTest
public class UpdateLeadSignedDateAndStatusTest {
	@isTest
    static void testTrigger_dateSignedUpdated_Lead() {
        
	//EvergreenIntegrationTest.testSendEvent();
        
        // Create a Lead
        Lead testLead = new Lead(
            FirstName = 'ASDG',
            LastName = 'ASDGF',
            Company = 'Test Company ASDGF'
        );
        insert testLead;
        
        // Create a HelloSign__HelloSign_Signature_Request__c record related to the Lead
        HelloSign__HelloSign_Signature_Request__c testRequest = new HelloSign__HelloSign_Signature_Request__c(
            HelloSign__Lead__c = testLead.Id
        );
        insert testRequest;
        
        // Create a HelloSign__HelloSign_Signature_Request_Detail__c record related to the request
        HelloSign__HelloSign_Signature_Request_Detail__c testDetail = new HelloSign__HelloSign_Signature_Request_Detail__c(
            HelloSign__HelloSign_Signature_Request__c = testRequest.Id,
            HelloSign__Date__c = Date.today(),
            HelloSign__Event__c = 'Signed'
        );
        insert testDetail;
        
        // Trigger should update the Lead's Signed_Date__c field
        List<Lead> updatedLeads = [SELECT Id, Date_Signed__c FROM Lead WHERE Id = :testLead.Id];
        System.assertEquals(Date.today(), updatedLeads[0].Date_Signed__c);
    }
    
    @isTest
    static void testTrigger_dateSentUpdated_Lead() {
        
	//EvergreenIntegrationTest.testSendEvent();
        
        // Create a Lead
        Lead testLead = new Lead(
            FirstName = 'ASDG',
            LastName = 'ASDGF',
            Company = 'Test Company ASDGF'
        );
        insert testLead;
        
        // Create a HelloSign__HelloSign_Signature_Request__c record related to the Lead
        HelloSign__HelloSign_Signature_Request__c testRequest = new HelloSign__HelloSign_Signature_Request__c(
            HelloSign__Lead__c = testLead.Id
        );
        insert testRequest;
        
        // Create a HelloSign__HelloSign_Signature_Request_Detail__c record related to the request
        HelloSign__HelloSign_Signature_Request_Detail__c testDetail = new HelloSign__HelloSign_Signature_Request_Detail__c(
            HelloSign__HelloSign_Signature_Request__c = testRequest.Id,
            HelloSign__Date__c = Date.today(),
            HelloSign__Event__c = 'Sent'
        );
        insert testDetail;
        
        // Trigger should update the Lead's Signed_Date__c field
        List<Lead> updatedLeads = [SELECT Id, Date_Retainer_Sent__c FROM Lead WHERE Id = :testLead.Id];
        System.assertEquals(Date.today(), updatedLeads[0].Date_Retainer_Sent__c);
    }
    
    @isTest
    static void testTrigger_dateSentUpdated_Talc() {   
	//EvergreenIntegrationTest.testSendEvent();
        
        // Create a Lead
        Lead testLead = new Lead(
            FirstName = 'ASDG',
            LastName = 'ASDGF',
            Company = 'Test Company ASDGF'
        );
        insert testLead;
        
        // Create a Talc	
        Talc__c testTalc = new Talc__c(
            Name = 'ASDG',
            Lead__c = testLead.Id
        );

 		insert testTalc;
        
        // Create a HelloSign__HelloSign_Signature_Request__c record related to the Talc
        HelloSign__HelloSign_Signature_Request__c testTalcRequest = new HelloSign__HelloSign_Signature_Request__c(
            Talc__c = testTalc.Id
        );
        insert testTalcRequest;
        
        HelloSign__HelloSign_Signature_Request_Detail__c testTalcDetail = new HelloSign__HelloSign_Signature_Request_Detail__c(
            HelloSign__HelloSign_Signature_Request__c = testTalcRequest.Id,
            HelloSign__Date__c = Date.today(),
            HelloSign__Event__c = 'Sent'
        );
        insert testTalcDetail;
        
        // Trigger should update the Lead's Date_Retainer_Sent__c field
        List<Lead> updatedLeads = [SELECT Id, Date_Signed__c, Date_Retainer_Sent__c FROM Lead WHERE Id = :testTalc.Lead__c];
        System.assertEquals(Date.today(), updatedLeads[0].Date_Retainer_Sent__c);
    }
}