force-app/main/default/objects/Lead/fields/Additional_Notes__c.field-meta.xml
<CustomField>
    <fullName>Additional_Notes__c</fullName>
    <description>Additional Notes field from the FormStack</description>
    <label>Additional Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Intake_Specialist__c.field-meta.xml
<CustomField>
    <fullName>Intake_Specialist__c</fullName>
    <label>Intake Specialist</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Roundup__c/Roundup__c.object-meta.xml
<CustomObject>
    <label>Roundup</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roundup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Roundup__c/fields/Any_Other_Tobacco_Products__c.field-meta.xml
<CustomField>
    <fullName>Any_Other_Tobacco_Products__c</fullName>
    <label>Any Other Tobacco Products</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Are_you_a_smoker__c.field-meta.xml
<CustomField>
    <fullName>Are_you_a_smoker__c</fullName>
    <label>Are you a smoker?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Begin_Smoking_Date__c.field-meta.xml
<CustomField>
    <fullName>Begin_Smoking_Date__c</fullName>
    <label>Begin Smoking Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Caller_Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Caller_Date_of_Birth__c</fullName>
    <label>Caller Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Cause_of_Death__c.field-meta.xml
<CustomField>
    <fullName>Cause_of_Death__c</fullName>
    <label>Cause of Death</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Chemotherapy_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Chemotherapy_End_Date__c</fullName>
    <label>Chemotherapy End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Chemotherapy_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Chemotherapy_Start_Date__c</fullName>
    <label>Chemotherapy Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Chemotherapy_Treatment_Information__c.field-meta.xml
<CustomField>
    <fullName>Chemotherapy_Treatment_Information__c</fullName>
    <label>Chemotherapy Treatment Information</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Injection</fullName>
            </value>
            <value>
                <fullName>Intraperitoneal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/City_and_State_Deceased__c.field-meta.xml
<CustomField>
    <fullName>City_and_State_Deceased__c</fullName>
    <label>City and State Deceased</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Confirm_Date_of_Death__c.field-meta.xml
<CustomField>
    <fullName>Confirm_Date_of_Death__c</fullName>
    <label>Confirm Date of Death</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DOD confirmed</fullName>
            </value>
            <value>
                <fullName>DOD not confirmed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Emergency_Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>Emergency_Contact_Phone__c</fullName>
    <label>Emergency Contact Phone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Emergency_Contact_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Emergency_Contact_Relationship__c</fullName>
    <label>Emergency Contact Relationship</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Employer_Address__c.field-meta.xml
<CustomField>
    <fullName>Employer_Address__c</fullName>
    <label>Employer Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Employer_City__c.field-meta.xml
<CustomField>
    <fullName>Employer_City__c</fullName>
    <label>Employer City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Employer_Name__c.field-meta.xml
<CustomField>
    <fullName>Employer_Name__c</fullName>
    <label>Employer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Employer_State__c.field-meta.xml
<CustomField>
    <fullName>Employer_State__c</fullName>
    <label>Employer State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Employer_Zip__c.field-meta.xml
<CustomField>
    <fullName>Employer_Zip__c</fullName>
    <label>Employer Zip</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/First_Treatment_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Treatment_Date__c</fullName>
    <label>First Treatment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Height_at_Date_of_Diagnosis__c.field-meta.xml
<CustomField>
    <fullName>Height_at_Date_of_Diagnosis__c</fullName>
    <label>Height at Date of Diagnosis</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Injured_Party_Deceased__c.field-meta.xml
<CustomField>
    <fullName>Injured_Party_Deceased__c</fullName>
    <label>Injured Party Deceased</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Injured_Party_Gender__c.field-meta.xml
<CustomField>
    <fullName>Injured_Party_Gender__c</fullName>
    <label>Injured Party Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Last_Treatment_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Treatment_Date__c</fullName>
    <label>Last Treatment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Roundup</relationshipLabel>
    <relationshipName>Roundup</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/NHL_Diagnosis_Stage__c.field-meta.xml
<CustomField>
    <fullName>NHL_Diagnosis_Stage__c</fullName>
    <label>NHL Diagnosis Stage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/NHL_Diagnosis_Year__c.field-meta.xml
<CustomField>
    <fullName>NHL_Diagnosis_Year__c</fullName>
    <label>NHL Diagnosis Year</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/NHL_Subtype__c.field-meta.xml
<CustomField>
    <fullName>NHL_Subtype__c</fullName>
    <label>NHL Subtype</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Occupation__c.field-meta.xml
<CustomField>
    <fullName>Occupation__c</fullName>
    <label>Occupation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agriculture Worker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Packs_of_Cigarettes_Per_Day__c.field-meta.xml
<CustomField>
    <fullName>Packs_of_Cigarettes_Per_Day__c</fullName>
    <label>Packs of Cigarettes Per Day</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Power_of_Attorney__c.field-meta.xml
<CustomField>
    <fullName>Power_of_Attorney__c</fullName>
    <label>Power of Attorney</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Quit_Smoking_Date__c.field-meta.xml
<CustomField>
    <fullName>Quit_Smoking_Date__c</fullName>
    <label>Quit Smoking Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Referral_Law_Firm__c.field-meta.xml
<CustomField>
    <fullName>Referral_Law_Firm__c</fullName>
    <label>Referral Law Firm</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Relationship_with_Injured_Contact__c.field-meta.xml
<CustomField>
    <fullName>Relationship_with_Injured_Contact__c</fullName>
    <label>Relationship with Injured Contact</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Roundup_First_Exposure_Date__c.field-meta.xml
<CustomField>
    <fullName>Roundup_First_Exposure_Date__c</fullName>
    <label>Roundup First Exposure Date</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Roundup_Last_Exposure_Date__c.field-meta.xml
<CustomField>
    <fullName>Roundup_Last_Exposure_Date__c</fullName>
    <label>Roundup Last Exposure Date</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Roundup_Total_Years_Used__c.field-meta.xml
<CustomField>
    <fullName>Roundup_Total_Years_Used__c</fullName>
    <label>Roundup Total Years Used</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Roundup_Usage_Location__c.field-meta.xml
<CustomField>
    <fullName>Roundup_Usage_Location__c</fullName>
    <label>Roundup Usage Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/State_of_Residence_during_Treatments__c.field-meta.xml
<CustomField>
    <fullName>State_of_Residence_during_Treatments__c</fullName>
    <label>State of Residence during Treatments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/States_Roundup_Used__c.field-meta.xml
<CustomField>
    <fullName>States_Roundup_Used__c</fullName>
    <label>States Roundup Used</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Surgeon_Address__c.field-meta.xml
<CustomField>
    <fullName>Surgeon_Address__c</fullName>
    <label>Surgeon Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Surgeon_City__c.field-meta.xml
<CustomField>
    <fullName>Surgeon_City__c</fullName>
    <label>Surgeon City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Surgeon_Name__c.field-meta.xml
<CustomField>
    <fullName>Surgeon_Name__c</fullName>
    <label>Surgeon Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Surgeon_State__c.field-meta.xml
<CustomField>
    <fullName>Surgeon_State__c</fullName>
    <label>Surgeon State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Surgeon_Zip__c.field-meta.xml
<CustomField>
    <fullName>Surgeon_Zip__c</fullName>
    <label>Surgeon Zip</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Treatment_Provider_Address__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Provider_Address__c</fullName>
    <label>Treatment Provider Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Treatment_Provider_City__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Provider_City__c</fullName>
    <label>Treatment Provider City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Treatment_Provider_Name__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Provider_Name__c</fullName>
    <label>Treatment Provider Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Treatment_Provider_Phone__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Provider_Phone__c</fullName>
    <label>Treatment Provider Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Treatment_Provider_State__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Provider_State__c</fullName>
    <label>Treatment Provider State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Treatment_Provider_Zip__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Provider_Zip__c</fullName>
    <label>Treatment Provider Zip</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Weight_at_Date_of_Diagnosis__c.field-meta.xml
<CustomField>
    <fullName>Weight_at_Date_of_Diagnosis__c</fullName>
    <label>Weight at Date of Diagnosis</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Roundup__c/fields/Years_Smoked__c.field-meta.xml
<CustomField>
    <fullName>Years_Smoked__c</fullName>
    <label>Years Smoked</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SmartAdvocateModel.cls
public class SmartAdvocateModel {

    public static List<Object> mapToSmartAdvocateFields(List<Roundup__c> records){
        List<Object> output = new List<Object>();
        
        for(Roundup__c record : records){
            Object intake;
            Map<String, String> mapToConvert = new Map<String, String>();
            mapToConvert.put('email', record.Lead__r.Email);
            mapToConvert.put('firstName', record.Lead__r.FirstName);
            mapToConvert.put('lastName', record.Lead__r.LastName);
            mapToConvert.put('phone', record.Lead__r.Phone);
            mapToConvert.put('Paid Advertisement', String.valueOf('RU: Consumer Tort Group (KKG)'));
            mapToConvert.put('Referral Law Firm', record.Referral_Law_Firm__c );
            mapToConvert.put('Referred Out Law Firm', 'Kline and Specter, PC');
            mapToConvert.put('Address', record.Lead__r.Street);
            mapToConvert.put('city', record.Lead__r.City);
            mapToConvert.put('state', record.Lead__r.State);
            mapToConvert.put('zip', record.Lead__r.PostalCode);
            mapToConvert.put('Intake Date', String.valueOF(record.Lead__r.CreatedDate));
            mapToConvert.put('dob', String.valueOF(record.Caller_Date_of_Birth__c));
            mapToConvert.put('gender', record.Injured_Party_Gender__c);
            mapToConvert.put('caseType', 'Roundup Herbicide');
            mapToConvert.put('ReferralLawFirm', record.Referral_Law_Firm__c);
            mapToConvert.put('PaidAdvertising', 'RU: Consumer Tort Group (KKG)');
            mapToConvert.put('ReferOutFirm', 'Kline and Specter, PC');

            mapToConvert.put('Agent Notes', record.Lead__r.Additional_Notes__c);
            mapToConvert.put('Agent Performing Interview Name', record.Lead__r.Intake_Specialist__c);
            mapToConvert.put('Best Contact Time', record.Best_Time_to_Reach__c);
            mapToConvert.put('POC Relationship to Injured Party', record.Relationship_with_Injured_Contact__c);
            mapToConvert.put('Best Contact Time POC', record.Best_Time_to_Reach__c); 
            mapToConvert.put('POC has Power of Attorney', record.Power_of_Attorney__c);
            mapToConvert.put('Is the injured party deceased?', record.Injured_Party_Deceased__c);
            mapToConvert.put('Confirm Date of Death in Contact Card', record.Confirm_Date_of_Death__c);
            mapToConvert.put('City and State where plaintiff was deceased (for example: Kansas City, MO):', record.City_and_State_Deceased__c);
            mapToConvert.put('Cause of Death', record.Cause_of_Death__c);
            mapToConvert.put('Emergency Contact First & Last Name', record.Emergency_Contact_Name__c);
            mapToConvert.put('Emergency Contact Relationship to Injured Party', record.Emergency_Contact_Relationship__c);
            mapToConvert.put('Emergency Contact Number', record.Emergency_Contact_Phone__c);
            mapToConvert.put('Exposure Type - Commercial/Residential', record.Roundup_Usage_Location__c);
            mapToConvert.put('Exposure Date To', record.Roundup_Last_Exposure_Date__c);
            mapToConvert.put('Exposure Date From', record.Roundup_First_Exposure_Date__c);
            mapToConvert.put('Duration of Exposure', record.Roundup_Total_Years_Used__c);
            mapToConvert.put('Location of Exposure', record.States_Roundup_Used__c);
            mapToConvert.put('Employer Name', record.Employer_Name__c);
            mapToConvert.put('Employer Address', record.Employer_Address__c);
            mapToConvert.put('Employer City', record.Employer_City__c);
            mapToConvert.put('Employer State', record.Employer_State__c);
            mapToConvert.put('Employer Zip', record.Employer_Zip__c);
            mapToConvert.put('Are you a Non-Smoker, Current Smoker, or Former Smoker?', record.Are_you_a_smoker__c);
            mapToConvert.put('Occupation', record.Occupation__c);
            mapToConvert.put('Occupation Other', record.Occupation__c);
            mapToConvert.put('When did you begin smoking?', String.valueOf(record.Begin_Smoking_Date__c));
            mapToConvert.put('If Current Smoker, how long have you smoked?', record.Years_Smoked__c);
            mapToConvert.put('Approximately how many packs of cigarettes a day did you smoke?', record.Packs_of_Cigarettes_Per_Day__c);
            mapToConvert.put('Any other tobacco products?', record.Any_Other_Tobacco_Products__c);
            mapToConvert.put('If Former Smoker, approximately when did you quit?', String.valueOf(record.Quit_Smoking_Date__c));
            //mapToConvert.put('Proof of Use', record.Cause_of_Death__c);
            
            mapToConvert.put('Type of Cancer', record.NHL_Subtype__c);
            if(record.NHL_Subtype__c != null) {
                mapToConvert.put('Other Cancer', record.NHL_Subtype__c.contains('Other') ? record.NHL_Subtype__c : '');
            }
            mapToConvert.put('Cancer Stage', record.NHL_Diagnosis_Stage__c);
            mapToConvert.put('Diagnosis Date', String.valueOf(record.NHL_Diagnosis_Year__c));
            mapToConvert.put('Height at Date of Diagnosis', record.Height_at_Date_of_Diagnosis__c);
            mapToConvert.put('Weight at Date of Diagnosis', record.Weight_at_Date_of_Diagnosis__c);
            mapToConvert.put('First Treatment Date', String.valueOf(record.First_Treatment_Date__c));
            mapToConvert.put('Last Treatment Date', String.valueOf(record.Last_Treatment_Date__c));
            mapToConvert.put('Chemotherapy Treatment Information', record.Chemotherapy_Treatment_Information__c);
			mapToConvert.put('Chemotherapy Start Date', String.valueOf(record.Chemotherapy_Start_Date__c));
			mapToConvert.put('Chemotherapy End Date', String.valueOf(record.Chemotherapy_End_Date__c));
            mapToConvert.put('Residence State During Treatments', record.State_of_Residence_during_Treatments__c);
			mapToConvert.put('Treatment Provider Name', record.Treatment_Provider_Name__c);
            mapToConvert.put('Treatment Provider Address', record.Treatment_Provider_Address__c);
            mapToConvert.put('Treatment Provider Phone', record.Treatment_Provider_Phone__c);
            mapToConvert.put('Treatment Provider City', record.Treatment_Provider_City__c);
            mapToConvert.put('Treatment Provider State', record.Treatment_Provider_State__c);
            mapToConvert.put('Treatment Provider Zip', record.Treatment_Provider_Zip__c);
            mapToConvert.put('Surgeon Name', record.Surgeon_Name__c);
            mapToConvert.put('Surgeon Address', record.Surgeon_Address__c);
            mapToConvert.put('Surgeon City', record.Surgeon_City__c);
            mapToConvert.put('Surgeon State', record.Surgeon_State__c);
            mapToConvert.put('Surgeon Zip', record.Surgeon_Zip__c);
            mapToConvert.put('Oncologist Name', record.Oncologist_Name__c);
            mapToConvert.put('Oncologist Address', record.Oncologist_Address__c);
            mapToConvert.put('Oncologist City', record.Oncologist_City__c);
            mapToConvert.put('Oncologist State', record.Oncologist_State__c);
            mapToConvert.put('Oncologist Zip', record.Oncologist_Zip__c);
            mapToConvert.put('PCP Name', record.PCP_Name__c);
            mapToConvert.put('PCP Address', record.PCP_Address__c);
            mapToConvert.put('PCP State', record.PCP_State__c);
            mapToConvert.put('PCP City', record.PCP_City__c);
            mapToConvert.put('PCP Zip', record.PCP_Zip__c);
            mapToConvert.put('Additional Specialist Information', record.Additional_Specialist_Information__c);
            mapToConvert.put('Medical History', record.Additional_Medical_History__c); 
            mapToConvert.put('Please indicate if you have any of the following:', record.Pre_existing_Conditions__c);
            mapToConvert.put('SSN', record.Lead__r.SSN__c);
            intake = mapToConvert;
            output.add(intake);
        }
	
        return output;
    }
}