force-app/main/default/objects/Lead/fields/Additional_Notes__c.field-meta.xml
<CustomField>
    <fullName>Additional_Notes__c</fullName>
    <description>Additional Notes field from the FormStack</description>
    <label>Additional Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Caller_Recorded_Consent__c.field-meta.xml
<CustomField>
    <fullName>Caller_Recorded_Consent__c</fullName>
    <label>Caller Recorded Consent</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Calling_for_yourself__c.field-meta.xml
<CustomField>
    <fullName>Calling_for_yourself__c</fullName>
    <label>Calling for yourself?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Self</fullName>
            </value>
            <value>
                <fullName>Someone Else</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Contacting_Consent__c.field-meta.xml
<CustomField>
    <fullName>Contacting_Consent__c</fullName>
    <description>Do we have full consents to reach out via phone, automated call, SMS/Text and email?</description>
    <label>Contacting Consent</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Signature_Mail_Request__c.field-meta.xml
<CustomField>
    <fullName>Signature_Mail_Request__c</fullName>
    <label>Signature/Mail Request</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>E-Signature</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <label>Time Zone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tylenol__c/Tylenol__c.object-meta.xml
<CustomObject>
    <label>Tylenol</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tylenol</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tylenol__c/fields/Accurate_Information_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Accurate_Information_Agreement__c</fullName>
    <label>Accurate Information Agreement</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tylenol__c/fields/ADHD_Medication_Brand__c.field-meta.xml
<CustomField>
    <fullName>ADHD_Medication_Brand__c</fullName>
    <label>ADHD Medication Brand</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Tylenol__c/fields/ADHD_Medication_Dosage__c.field-meta.xml
<CustomField>
    <fullName>ADHD_Medication_Dosage__c</fullName>
    <label>ADHD Medication Dosage</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Tylenol__c/fields/ADHD_Medication_Duration__c.field-meta.xml
<CustomField>
    <fullName>ADHD_Medication_Duration__c</fullName>
    <label>ADHD Medication Duration</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Tylenol__c/fields/Alternate_Contact_Number__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Contact_Number__c</fullName>
    <label>Alternate Contact Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Tylenol__c/fields/Child_Born_After_Week_26__c.field-meta.xml
<CustomField>
    <fullName>Child_Born_After_Week_26__c</fullName>
    <label>Child Born After Week 26</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Week 25 or before (DNQ)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tylenol__c/fields/Child_Diagnosed_with_ADHD__c.field-meta.xml
<CustomField>
    <fullName>Child_Diagnosed_with_ADHD__c</fullName>
    <label>Child Diagnosed with ADHD</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tylenol__c/fields/Child_Formally_Diagnosed__c.field-meta.xml
<CustomField>
    <fullName>Child_Formally_Diagnosed__c</fullName>
    <label>Child Formally Diagnosed</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ADHD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tylenol__c/fields/Child_s_Birth_City__c.field-meta.xml
<CustomField>
    <fullName>Child_s_Birth_City__c</fullName>
    <label>Child&apos;s Birth City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tylenol__c/fields/Child_s_Birth_Facility_and_Address__c.field-meta.xml
<CustomField>
    <fullName>Child_s_Birth_Facility_and_Address__c</fullName>
    <description>What is the name of the birth facilities and address where the child was born?</description>
    <label>Child&apos;s Birth Facility and Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Tylenol__c/fields/Child_s_Birth_State__c.field-meta.xml
<CustomField>
    <fullName>Child_s_Birth_State__c</fullName>
    <label>Child&apos;s Birth State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tylenol__c/fields/Child_s_Birth_Week__c.field-meta.xml
<CustomField>
    <fullName>Child_s_Birth_Week__c</fullName>
    <label>Child&apos;s Birth Week</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tylenol__c/fields/Child_s_Birth_Zip__c.field-meta.xml
<CustomField>
    <fullName>Child_s_Birth_Zip__c</fullName>
    <label>Child&apos;s Birth Zip</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tylenol__c/fields/Child_s_Current_Age__c.field-meta.xml
<CustomField>
    <fullName>Child_s_Current_Age__c</fullName>
    <label>Child&apos;s Current Age</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tylenol__c/fields/Child_s_Diagnosis_Date__c.field-meta.xml
<CustomField>
    <fullName>Child_s_Diagnosis_Date__c</fullName>
    <label>Child&apos;s Diagnosis Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Tylenol__c/fields/Child_s_SSN__c.field-meta.xml
<CustomField>
    <fullName>Child_s_SSN__c</fullName>
    <label>Child&apos;s SSN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tylenol__c/fields/Client_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Name__c</fullName>
    <label>Client Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tylenol__c/fields/Date_of_Passing__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Passing__c</fullName>
    <label>Date of Passing</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Tylenol__c/fields/Diagnosing_Physician_Hospital_Address__c.field-meta.xml
<CustomField>
    <fullName>Diagnosing_Physician_Hospital_Address__c</fullName>
    <description>What is the name of the diagnosing physician, hospital and address where the child received the diagnosis?</description>
    <label>Diagnosing Physician, Hospital, Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Tylenol__c/fields/Frequency_of_Tylenol_Use__c.field-meta.xml
<CustomField>
    <fullName>Frequency_of_Tylenol_Use__c</fullName>
    <description>Approximately how many times did you take Tylenol during the 2nd or 3rd  trimester of your pregnancy?</description>
    <inlineHelpText>Approximately how many times did you take Tylenol during the 2nd or 3rd  trimester of your pregnancy?</inlineHelpText>
    <label>Frequency of Tylenol Use</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Other:</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tylenol__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tylenol__c/fields/Generic_Acetaminophen_Store__c.field-meta.xml
<CustomField>
    <fullName>Generic_Acetaminophen_Store__c</fullName>
    <label>Generic Acetaminophen Store</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Walmart</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tylenol__c/fields/Has_Power_of_Attorney__c.field-meta.xml
<CustomField>
    <fullName>Has_Power_of_Attorney__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Power of Attorney</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tylenol__c/fields/Is_Next_of_Kin__c.field-meta.xml
<CustomField>
    <fullName>Is_Next_of_Kin__c</fullName>
    <label>Is Next of Kin</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tylenol__c/fields/Is_Person_Deceased__c.field-meta.xml
<CustomField>
    <fullName>Is_Person_Deceased__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Person Deceased</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tylenol__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Tylenol</relationshipLabel>
    <relationshipName>Tylenol</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tylenol__c/fields/Mother_s_Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Mother_s_Date_of_Birth__c</fullName>
    <label>Mother&apos;s Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Tylenol__c/fields/Other_Behavioral_Psychological_Issues__c.field-meta.xml
<CustomField>
    <fullName>Other_Behavioral_Psychological_Issues__c</fullName>
    <label>Other Behavioral/Psychological Issues</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tylenol__c/fields/Other_Generic_Acetaminophen_Store__c.field-meta.xml
<CustomField>
    <fullName>Other_Generic_Acetaminophen_Store__c</fullName>
    <label>Other Generic Acetaminophen Store</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Tylenol__c/fields/Relationship_with_Client__c.field-meta.xml
<CustomField>
    <fullName>Relationship_with_Client__c</fullName>
    <label>Relationship with Client</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Tylenol__c/fields/Represented_by_Law_Firm__c.field-meta.xml
<CustomField>
    <fullName>Represented_by_Law_Firm__c</fullName>
    <label>Represented by Law Firm</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes (DNQ)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tylenol__c/fields/Trimester_of_Tylenol_Use__c.field-meta.xml
<CustomField>
    <fullName>Trimester_of_Tylenol_Use__c</fullName>
    <description>Approximately what trimester in your pregnancy did you take Tylenol (also  known as Acetaminophen or Paracetamol)?</description>
    <inlineHelpText>Approximately what trimester in your pregnancy did you take Tylenol (also  known as Acetaminophen or Paracetamol)?</inlineHelpText>
    <label>Trimester of Tylenol Use</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1st trimester (DNQ)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tylenol__c/fields/Tylenol_Acetaminophen_Taken__c.field-meta.xml
<CustomField>
    <fullName>Tylenol_Acetaminophen_Taken__c</fullName>
    <description>When you took Tylenol/generic Acetaminophen, what did you normally take?</description>
    <label>Tylenol/Acetaminophen Taken</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>250mg (1 regular strength)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tylenol__c/fields/Tylenol_Brand__c.field-meta.xml
<CustomField>
    <fullName>Tylenol_Brand__c</fullName>
    <label>Tylenol Brand</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tylenol Brand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tylenol__c/fields/Type_of_Disorder__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Disorder__c</fullName>
    <label>Type of Disorder</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Autism Spectrum Disorder</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TylenolTriggerHandler.cls
public class TylenolTriggerHandler {
	public static void sendTylenolRecordsToEvergreen(Id recordId) {
     	List <Tylenol__c> newTylenolRecord = [SELECT Lead__c, Lead__r.Id, Lead__r.FirstName, Lead__r.MiddleName, Lead__r.LastName, Lead__r.City,Lead__r.State, Lead__r.Street, Lead__r.PostalCode, Lead__r.Time_Zone__c,
                                    Lead__r.Phone, Lead__r.Contacting_Consent__c, Lead__r.Email, Lead__r.Status, Lead__r.CreatedDate, Lead__r.Calling_for_yourself__c, Lead__r.Signature_Mail_Request__c,
                                    Lead__r.Additional_Notes__c, Lead__r.Caller_Recorded_Consent__c, Accurate_Information_Agreement__c, Relationship_with_Client__c, Client_Name__c, 
                                    Date_of_Birth__c, Gender__c, Child_s_SSN__c, Is_Person_Deceased__c, Has_Power_of_Attorney__c, Is_Next_of_Kin__c, Date_of_Passing__c, Mother_s_Date_of_Birth__c, 
                                    Alternate_Contact_Number__c, Represented_by_Law_Firm__c, Trimester_of_Tylenol_Use__c, Tylenol_Acetaminophen_Taken__c, Tylenol_Brand__c, Generic_Acetaminophen_Store__c, 
                                    Other_Generic_Acetaminophen_Store__c, Frequency_of_Tylenol_Use__c, Child_Born_After_Week_26__c, Child_s_Birth_Week__c, Child_s_Current_Age__c, 
                                    Child_Formally_Diagnosed__c, Type_of_Disorder__c, Child_s_Diagnosis_Date__c, Diagnosing_Physician_Hospital_Address__c, Child_s_Birth_Facility_and_Address__c, 
                                    Child_s_Birth_City__c, Child_s_Birth_State__c, Child_s_Birth_Zip__c, Child_Diagnosed_with_ADHD__c, ADHD_Medication_Brand__c, ADHD_Medication_Dosage__c, 
                                    ADHD_Medication_Duration__c, Other_Behavioral_Psychological_Issues__c, Issue_Description_and_Severity__c, Child_Held_Back_in_School__c, Tutoring_Therapy_Expenses__c, 
                                    Other_ADHD_Issues_Concerns__c, Specific_Diagnoses__c, Complications_During_Pregnancy__c, Substance_Use_During_Pregnancy__c, Your_Age_at_Baby_s_Birth__c, Mother_s_Full_Name__c, 
                                    Father_s_Full_Name__c, Father_s_Age_at_Baby_s_Birth__c, Diagnosed_with_Autism_or_ADHD__c, Mother_s_SSN__c, Emergency_Contact_Name__c, Emergency_Contact_Relationship__c, 
                                    Emergency_Phone__c FROM Tylenol__c WHERE Id = :recordId];
        
		if (newTylenolRecord != null && !newTylenolRecord.isEmpty()) {
            List<Object> evergreenModels = MapToEvergreen.mapToEvergreenFields(newTylenolRecord[0]);
            // Convert EvergreenModel to JSON
            String evergreenModelsJson = JSON.serialize(evergreenModels[0]);

            // Asynchronously send data to the external system
            EvergreenIntegration.sendLeadDataAsync(evergreenModelsJson);
        }
	}
}