force-app/main/default/objects/Lead/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <label>SSN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Talc__c/Talc__c.object-meta.xml
<CustomObject>
    <label>Talc</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Talcs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Talc__c/fields/Alternate_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Phone_Number__c</fullName>
    <label>Alternate Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Talc__c/fields/Best_Time_to_Reach__c.field-meta.xml
<CustomField>
    <fullName>Best_Time_to_Reach__c</fullName>
    <label>Best Time to Reach</label>
    <length>12768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Talc__c/fields/Currently_Smoke_Cigarettes__c.field-meta.xml
<CustomField>
    <fullName>Currently_Smoke_Cigarettes__c</fullName>
    <label>Currently Smoke Cigarettes</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Talc__c/fields/Fallopian_Tubes_Removed_During_Surgery__c.field-meta.xml
<CustomField>
    <fullName>Fallopian_Tubes_Removed_During_Surgery__c</fullName>
    <label>Fallopian Tubes Removed During Surgery</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Talc__c/fields/Family_History_Ovarian_Breast_Cancer__c.field-meta.xml
<CustomField>
    <fullName>Family_History_Ovarian_Breast_Cancer__c</fullName>
    <description>Limiting this question to blood relatives, to the best of your knowledge, Do you have any  parents,  siblings, children, grandparents, aunts, uncles, or first cousins have ever suffered from or been treated for (ONLY) ovarian cancer or breast cancer?</description>
    <label>Family History Ovarian Breast Cancer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Talc__c/fields/Filed_Claim_in_Imerys_Bankruptcy__c.field-meta.xml
<CustomField>
    <fullName>Filed_Claim_in_Imerys_Bankruptcy__c</fullName>
    <label>Filed Claim in Imerys Bankruptcy</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Talc__c/fields/Filed_Lawsuit_for_Ovarian_Cancer__c.field-meta.xml
<CustomField>
    <fullName>Filed_Lawsuit_for_Ovarian_Cancer__c</fullName>
    <label>Filed Lawsuit for Ovarian Cancer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Talc__c/fields/Formally_Released__c.field-meta.xml
<CustomField>
    <fullName>Formally_Released__c</fullName>
    <label>Formally Released</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Talc__c/fields/Had_a_Tubal_Ligation__c.field-meta.xml
<CustomField>
    <fullName>Had_a_Tubal_Ligation__c</fullName>
    <label>Had a Tubal Ligation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Talc__c/fields/Injureds_Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Injureds_Date_of_Birth__c</fullName>
    <label>Injured&apos;s Date of Birth?</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Talc__c/fields/Injureds_date_of_death__c.field-meta.xml
<CustomField>
    <fullName>Injureds_date_of_death__c</fullName>
    <label>Injured&apos;s date of death?</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Talc__c/fields/Injureds_Full_Legal_Name__c.field-meta.xml
<CustomField>
    <fullName>Injureds_Full_Legal_Name__c</fullName>
    <label>Injured&apos;s Full Legal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Talc__c/fields/Injureds_Gender__c.field-meta.xml
<CustomField>
    <fullName>Injureds_Gender__c</fullName>
    <description>What is your Gender?*</description>
    <inlineHelpText>What is your Gender?*</inlineHelpText>
    <label>Injured&apos;s Gender?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Man</fullName>
            </value>
            <value>
                <fullName>Woman</fullName>
            </value>
            <value>
                <fullName>Non-Binary</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Talc__c/fields/Is_Injured_deceased__c.field-meta.xml
<CustomField>
    <fullName>Is_Injured_deceased__c</fullName>
    <label>Is Injured/Client deceased?</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Talc__c/fields/Last_Visit_Year_PC_Prov_5__c.field-meta.xml
<CustomField>
    <fullName>Last_Visit_Year_PC_Prov_5__c</fullName>
    <label>Last Visit Year - PC Prov 5</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Talc__c/fields/Lawyer_Name_and_Contact_Information__c.field-meta.xml
<CustomField>
    <fullName>Lawyer_Name_and_Contact_Information__c</fullName>
    <label>Lawyer Name and Contact Information</label>
    <length>12768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Talc__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>WattsGuerraTalcQuestionnaireV2FINAL_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Talc__c/fields/Legal_authority_to_represent_Injured__c.field-meta.xml
<CustomField>
    <fullName>Legal_authority_to_represent_Injured__c</fullName>
    <description>Do you have legal authority to represent [say injured person’s name] claim?*</description>
    <inlineHelpText>Do you have legal authority to represent Injured claim?*</inlineHelpText>
    <label>Legal authority to represent Injured?</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Talc__c/fields/Maiden_Other_Names_Used__c.field-meta.xml
<CustomField>
    <fullName>Maiden_Other_Names_Used__c</fullName>
    <label>Maiden/Other Names Used</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Talc__c/fields/Marital_Status__c.field-meta.xml
<CustomField>
    <fullName>Marital_Status__c</fullName>
    <label>Marital Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Married</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Talc__c/fields/Monthyear_started_using_product__c.field-meta.xml
<CustomField>
    <fullName>Monthyear_started_using_product__c</fullName>
    <description>Approximately what month and year did you START using the product regularly?</description>
    <inlineHelpText>Approximately what month and year did you START using the product regularly?</inlineHelpText>
    <label>Month\year started using product?</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Talc__c/fields/Name_of_the_legal_authority__c.field-meta.xml
<CustomField>
    <fullName>Name_of_the_legal_authority__c</fullName>
    <label>Name of the legal authority</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Talc__c/fields/Next_Of_Kin__c.field-meta.xml
<CustomField>
    <fullName>Next_Of_Kin__c</fullName>
    <label>Next Of Kin</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Talc__c/fields/Number_of_Pharmacies_Used__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Pharmacies_Used__c</fullName>
    <label>Number of Pharmacies Used</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Talc__c/fields/Number_of_Pre_cancer_Providers_Visited__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Pre_cancer_Providers_Visited__c</fullName>
    <label>Number of Pre-cancer Providers Visited</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Talc__c/fields/Number_of_Providers__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Providers__c</fullName>
    <label>Number of Providers</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Talc__c/fields/Number_of_Unidentified_Cancer_Providers__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Unidentified_Cancer_Providers__c</fullName>
    <label>Number of Unidentified Cancer Providers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Talc__c/fields/Ovaries_Removed_During_Surgery__c.field-meta.xml
<CustomField>
    <fullName>Ovaries_Removed_During_Surgery__c</fullName>
    <label>Ovaries Removed During Surgery</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Talc__c/fields/Past_Smoked_Cigarettes__c.field-meta.xml
<CustomField>
    <fullName>Past_Smoked_Cigarettes__c</fullName>
    <label>Past Smoked Cigarettes</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Talc__c/fields/Previously_represented_by_Attorney__c.field-meta.xml
<CustomField>
    <fullName>Previously_represented_by_Attorney__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Were you previously represented by an attorney in this case?</description>
    <inlineHelpText>Were you previously represented by an attorney in this case?</inlineHelpText>
    <label>Previously represented by Attorney?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Talc__c/fields/Reason_for_Release__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Release__c</fullName>
    <label>Reason for Release</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Talc__c/fields/Release_Preference__c.field-meta.xml
<CustomField>
    <fullName>Release_Preference__c</fullName>
    <inlineHelpText>Do you want to be released?</inlineHelpText>
    <label>Release Preference</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Talc__c/fields/Spouse_s_Name__c.field-meta.xml
<CustomField>
    <fullName>Spouse_s_Name__c</fullName>
    <label>Spouse&apos;s Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Talc__c/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <label>SSN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Talc__c/fields/Used_Johnson_Johnson_Powder__c.field-meta.xml
<CustomField>
    <fullName>Used_Johnson_Johnson_Powder__c</fullName>
    <label>Used Johnson &amp; Johnson Powder</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Talc__c/fields/Used_Johnson_Johnson_Shower__c.field-meta.xml
<CustomField>
    <fullName>Used_Johnson_Johnson_Shower__c</fullName>
    <label>Used Johnson &amp; Johnson Shower</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Talc__c/fields/Your_relation_to_the_injured__c.field-meta.xml
<CustomField>
    <fullName>Your_relation_to_the_injured__c</fullName>
    <label>Your relation to the injured</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Value1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EvergreenModelTalc.cls
public class EvergreenModelTalc extends EvergreenModel{
	// Fields specific to Talc__c
    public String NextofKinorLegalRep;
    public String LegalAuthority;
    public String PreviouslyUsedNameFirst;
    public String PreviouslyUsedNameLast;
    public String LegalConfirmationOfRep;
    public String SpouseFirstName;
	public String SpouseLastName;
	public String SpouseMiddleName;
    //public String CauseOfDeathOnDeathCertificate;
    public String AlternateEmail;
    public String AlternatePhone;
    //public String InjuredPartyPhone;
    public String PreferredMethodOfCommunication;
    public String BestTimeToReach;
    //public String ContactingConsent;
    public String WantsDisengagedFromPrevRep;
    public String HaveYouBeenFormallyReleased;
    public String WhyHaveYouBeenReleased;
    public String UsedJJBP;
    public String UsedJJSS;
    public String ProviderInformedPotentialCause;
    public String OtherExposure;
    public String FirstLearnAboutTort;
    public String OtherCancerDx;
    public String OTCProviderPrefix;
    public String OTCProviderFirstName;
    public String OTCProviderMiddleName;
    public String OTCProviderLastName;
    public String TestedForBRCAMutation;
    public String DxWithObesityClinicallyOverweight;
    public String FamHistoryOfOvarianBreastCancer;
    public String RelativesWithGeneticMutations;
    public String ProviderCountLast10Years;
    public Date LastYearOfProviderVisit;
    public String CancerRelatedProviderCount;
    public String PreCancerProviderCountLast10Yrs;
    public String PharmaciesUsedCountLast10Years;
    public String CurrentlySmoke;
    public String SmokedCigarettes;
    public String PersonallyFiledSuitOvarianCancer;
    public String FiledSuitImerysBankruptcy;
    public String OvariesRemoved;
    public String FallopianTubesRemoved;
    public String PrevRepDoYouWantToBeReleased;
    public String InjuredPartyGender;
    public String LegalAuthorityVerified;
    public String TubalLigation;
    public String ExposedLocation;
    public String MassTortName;
    
    public List<AilmentData> plAilmentDataList = new List<AilmentData>();

    public EvergreenModelTalc(Talc__c talcObject) {
        super(talcObject.Lead__r);
        MassTortName = 'Talc';
        
        // Map fields specific to Talc__c
        if (talcObject.Injureds_Full_Legal_Name__c != null){
            InjuredPartyFirstName = talcObject.Injureds_Full_Legal_Name__c?.contains(' ') ? talcObject.Injureds_Full_Legal_Name__c?.split(' ')[0] : talcObject.Injureds_Full_Legal_Name__c;
        	//InjuredPartyMiddleName = talcObject.Injureds_Full_Legal_Name__c;
			InjuredPartyLastName = talcObject.Injureds_Full_Legal_Name__c?.contains(' ') ? talcObject.Injureds_Full_Legal_Name__c?.split(' ')[1] : talcObject.Injureds_Full_Legal_Name__c;
        }
		LegalConfirmationOfRep = talcObject.Previously_represented_by_Attorney__c == true ? 'Yes' : 'No';
		Lovedonealiveordeceased =  talcObject.Is_Injured_deceased__c == 'Yes' ? 'Deceased' : 'Alive';
		InjuredPartyDateofDeath = talcObject.Injureds_date_of_death__c;
		InjuredPartyDateofBirth = talcObject.Injureds_Date_of_Birth__c;
		InjuredPartyMaritalStatus = talcObject.Marital_Status__c;
		AlternatePhone = talcObject.Alternate_Phone_Number__c;
        NextofKinorLegalRep = talcObject.Next_Of_Kin__c;
        ExposureStartDate = talcObject.Monthyear_started_using_product__c;
        PreviouslyUsedNameFirst = talcObject.Maiden_Other_Names_Used__c;
        PreviouslyUsedNameLast = talcObject.Maiden_Other_Names_Used__c;
        InjuredPartySSN = talcObject.SSN__C;
        if(talcObject.Spouse_s_Name__c != null){
        	SpouseFirstName = talcObject.Spouse_s_Name__c?.contains(' ') ? talcObject.Spouse_s_Name__c?.split(' ')[0] : talcObject.Spouse_s_Name__c;
        	SpouseLastName = talcObject.Spouse_s_Name__c?.contains(' ') ? talcObject.Spouse_s_Name__c?.split(' ')[1] : talcObject.Spouse_s_Name__c;
        }
        WantsDisengagedFromPrevRep = talcObject.Lawyer_Name_and_Contact_Information__c;
        HaveYouBeenFormallyReleased = talcObject.Formally_Released__c;
        WhyHaveYouBeenReleased = talcObject.Reason_for_Release__c;
        PrevRepDoYouWantToBeReleased = talcObject.Release_Preference__c;
        UsedJJBP = talcObject.Used_Johnson_Johnson_Powder__c;
        UsedJJSS = talcObject.Used_Johnson_Johnson_Shower__c;
        CancerRelatedProviderCount = talcObject.Number_of_Unidentified_Cancer_Providers__c;
        PreCancerProviderCountLast10Yrs = talcObject.Number_of_Pre_cancer_Providers_Visited__c;
        ProviderCountLast10Years = talcObject.Number_of_Providers__c;
        LastYearOfProviderVisit = talcObject.Last_Visit_Year_PC_Prov_5__c;
        PharmaciesUsedCountLast10Years = talcObject.Number_of_Pharmacies_Used__c;
        CurrentlySmoke = talcObject.Currently_Smoke_Cigarettes__c;
		SmokedCigarettes = talcObject.Past_Smoked_Cigarettes__c;
		PersonallyFiledSuitOvarianCancer = talcObject.Filed_Lawsuit_for_Ovarian_Cancer__c;
		FiledSuitImerysBankruptcy = talcObject.Filed_Claim_in_Imerys_Bankruptcy__c;
        BestTimeToReach = talcObject.Best_Time_to_Reach__c;
		OvariesRemoved = talcObject.Ovaries_Removed_During_Surgery__c;
		FallopianTubesRemoved = talcObject.Fallopian_Tubes_Removed_During_Surgery__c;       
        InjuredPartyGender = talcObject.Injureds_Gender__c;
        LegalAuthorityVerified = talcObject.Legal_authority_to_represent_Injured__c;
        LegalAuthority = talcObject.Name_of_the_legal_authority__c;
        TubalLigation = talcObject.Had_a_Tubal_Ligation__c;          
        RelationshipToInjuredParty = talcObject.Your_relation_to_the_injured__c;
        FamHistoryOfOvarianBreastCancer = talcObject.Family_History_Ovarian_Breast_Cancer__c;
        RelativesWithGeneticMutations = talcObject.Family_History_Genetic_Mutations__c;
        SoughtCompensationAlready = talcObject.Represented_By_Law_Firm__c;
		ExposedLocation = talcObject.Where_did_you_apply_product__c;
		//ProviderInformedPotentialCause = 
		OtherExposure = talcObject.Used_Other_Cosmetic_Powder_Products__c;
		ExposureEndDate = talcObject.Monthyear_stopped_using_product__c;
		FirstLearnAboutTort = talcObject.Time_of_Connection_Awareness__c;
		TestedForBRCAMutation = talcObject.Tested_for_the_BRCA1_or_BRCA2_mutation__c;
		OtherCancerDx = talcObject.Diagnosed_with_Other_Cancer__c;
		//OTCProviderPrefix = 
		OTCProviderFirstName = talcObject.Diagnosing_Doctor__c;
		//OTCProviderMiddleName = 
		OTCProviderLastName = talcObject.Diagnosing_Doctor__c;
		DxWithObesityClinicallyOverweight = talcObject.Diagnosed_with_Obesity_Overweight__c;
        //TimeZone = talcObject.Time_Zone__c;

        List<String> selectedAilments = talcObject?.Injury_diagnosed_with__c?.split(';');
        if(selectedAilments != null && !selectedAilments.isEmpty()) {
            for (String ailment : selectedAilments) {
                AilmentData ailmentData = new AilmentData(); // Initialize AilmentData
                ailmentData.Ailment = ailment.trim();
                if(ailmentData.Ailment == 'Mesothelioma') {
                    ailmentData.DateOfDiagnosis = talcObject.First_diagnosed_mesothelioma__c;
                } else if(ailmentData.Ailment == 'Primary Peritoneal') {
                    ailmentData.DateOfDiagnosis = talcObject.First_diagnosed_primary_peritoneal__c;
                    ailmentData.AilmentTypeSpecific = talcObject.Cancer_Type_at_Dx__c;
                    ailmentData.AilmentStage = talcObject.Cancer_Stage_at_Dx__c;
                } else if(ailmentData.Ailment == 'Fallopian Tube Cancer') {
                    ailmentData.DateOfDiagnosis = talcObject.First_diagnosed_fallopian_tube__c;
                    ailmentData.AilmentTypeSpecific = talcObject.Cancer_Type_at_Dx__c;
                    ailmentData.AilmentStage = talcObject.Cancer_Stage_at_Dx__c;    
                } else if(ailmentData.Ailment == 'Ovarian Cancer') {
                    ailmentData.DateOfDiagnosis = talcObject.First_diagnosed_ovarian_cancer__c;
                    ailmentData.AilmentTypeSpecific = talcObject.Cancer_Type_at_Dx__c;
                    ailmentData.AilmentStage = talcObject.Cancer_Stage_at_Dx__c;
                } else if(ailmentData.Ailment == 'Cervical Cancer') {
                    ailmentData.DateOfDiagnosis = talcObject.First_diagnosed_cervical_cancer__c;
                } else if(ailmentData.Ailment == 'Uterine Cancer') {
                    ailmentData.DateOfDiagnosis = talcObject.First_diagnosed_uterine_cancer__c;
                } else if(ailmentData.Ailment == 'Vaginal Cancer') {
                    ailmentData.DateOfDiagnosis = talcObject.First_diagnosed_vaginal_cancer__c;
                } else if(ailmentData.Ailment == 'Vulvar Cancer') {
                    //ailmentData.DateOfDiagnosis = talcObject.First_diagnosed_vulvar_cancer__c;
                } else if(ailmentData.Ailment == 'Endometrial cancer') {
                    ailmentData.DateOfDiagnosis = talcObject.First_diagnosed_endometerial_cancer__c;
                }
                plAilmentDataList.add(ailmentData);
            }
        }
    }
        
    public class AilmentData {
        public Date DateOfDiagnosis;
        public String Ailment;
        public String AilmentTypeSpecific;
        public String AilmentStage;
	}
}